-- MySQL Script generated by MySQL Workbench
-- Sat Jun 11 19:46:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema Warrior
-- -----------------------------------------------------
CREATE SCHEMA `Warrior` DEFAULT CHARACTER SET utf8;
USE `Warrior` ;

-- -----------------------------------------------------
-- Table `Warrior`.`Tipos De Usuario`
-- -----------------------------------------------------
CREATE TABLE `Warrior`.`Tipos De Usuario` (
  `id_TiposDeUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_TiposDeUsuario`));


-- -----------------------------------------------------
-- Table `Warrior`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE `Warrior`.`Usuario` (
  `id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Usuario` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(255) NULL,
  `Foto_Perfil` BLOB NULL,
  `Tipo_Usuario` INT NOT NULL,
  PRIMARY KEY (`id_Usuario`),
  INDEX `Tipo_Usuario_idx` (`Tipo_Usuario` ASC),
  CONSTRAINT `Tipo_Usuario`
    FOREIGN KEY (`Tipo_Usuario`)
    REFERENCES `Warrior`.`Tipos De Usuario` (`id_TiposDeUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `Warrior`.`Producto`
-- -----------------------------------------------------
CREATE TABLE `Warrior`.`Producto` (
  `id_Producto` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Producto` VARCHAR(45) NOT NULL,
  `Tipo_Producto` VARCHAR(45) NOT NULL,
  `Precio` DECIMAL NOT NULL,
  `Foto_Producto` BLOB NOT NULL,
  PRIMARY KEY (`id_Producto`));


-- -----------------------------------------------------
-- Table `Warrior`.`Peleas`
-- -----------------------------------------------------
CREATE TABLE `Warrior`.`Peleas` (
  `id_Peleas` INT NOT NULL AUTO_INCREMENT,
  `Ganadas` INT NOT NULL,
  `Perdidas` INT NOT NULL,
  `Empatadas` INT NOT NULL,
  `Sin Resultado` INT NOT NULL,
  PRIMARY KEY (`id_Peleas`));


-- -----------------------------------------------------
-- Table `Warrior`.`Competidor`
-- -----------------------------------------------------
CREATE TABLE `Warrior`.`Competidor` (
  `id_Competidor` INT NOT NULL AUTO_INCREMENT,
  `id_Usuario` INT NOT NULL,
  `Descripción_Competidor` VARCHAR(255) NULL,
  `Foto_Competidor` BLOB NULL,
  `Total_Peleas` INT NOT NULL,
  PRIMARY KEY (`id_Competidor`),
  INDEX `Total_Peleas_idx` (`Total_Peleas` ASC),
  INDEX `id_Usuario_idx` (`id_Usuario` ASC),
  CONSTRAINT `Total_Peleas`
    FOREIGN KEY (`Total_Peleas`)
    REFERENCES `Warrior`.`Peleas` (`id_Peleas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_Usuario`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `Warrior`.`Usuario` (`id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
