-- MySQL Script generated by MySQL Workbench
-- Sat Jun 11 19:46:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema Warrior
-- -----------------------------------------------------
CREATE SCHEMA `Warrior` DEFAULT CHARACTER SET utf8;
USE `Warrior` ;

-- -----------------------------------------------------
-- Table `Warrior`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE `Warrior`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Usuario`));


-- -----------------------------------------------------
-- Table `Warrior`.`Producto`
-- -----------------------------------------------------
CREATE TABLE `Warrior`.`Producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(45) NOT NULL,
  `precio` DECIMAL NOT NULL,
  `imagen` BLOB NOT NULL,
  PRIMARY KEY (`id_producto`));



-- -----------------------------------------------------
-- Table `Warrior`.`Competidores`
-- -----------------------------------------------------
CREATE TABLE `Warrior`.`competidores` (
  `id_competidor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `foto` BLOB NULL,
  `peleas` INT NOT NULL,
  `ganadas` INT NOT NULL,
  `perdidas` INT NOT NULL,
  `empatadas` INT NOT NULL,
  `sin_resultado` INT NOT NULL,
  PRIMARY KEY (`id_Competidor`),
  INDEX `peleas_idx` (`peleas` ASC),
  CONSTRAINT `peleas`
    FOREIGN KEY (`peleas`)
    REFERENCES `Warrior`.`Peleas` (`id_Peleas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_Usuario`
    FOREIGN KEY (`id_Usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
-- -----------------------------------------------------
-- Table `Warrior`.`Foro`
-- -----------------------------------------------------
CREATE TABLE `Warrior`.`foro` (
  `id` int(7) NOT NULL auto_increment,
  `Usuario` varchar(200) NOT NULL default '',
  `titulo` varchar(200) NOT NULL default '',
  `mensaje` text NOT NULL,
  `fecha` datetime NOT NULL default '0000-00-00 00:00:00',
  `respuestas` int(11) NOT NULL default '0',
  `identificador` int(7) NOT NULL default '0',
  `ult_respuesta` datetime default NULL,
  KEY `id` (`id`)
) TYPE=MyISAM;

-- -----------------------------------------------------
-- Table `Warrior`.`horarios`
-- -----------------------------------------------------
CREATE TABLE `Warrior`.`horarios` (
`id_horarios` int(7) NOT NULL auto_increment PRIMARY KEY,
`imagen` BLOB NOT NULL,
);
-- -----------------------------------------------------
-- Table `Warrior`.`rutinas`
-- -----------------------------------------------------
CREATE TABLE `Warrior`.`rutinas` (
`id_rutina` int(7) NOT NULL auto_increment PRIMARY KEY,
`producto` varchar(200) NOT NULL default '',
`link` varchar(200) NOT NULL default '',
);
-- -----------------------------------------------------
-- Table `Warrior`.`contactos`
-- -----------------------------------------------------
CREATE TABLE `Warrior`.`contactos` (
`id_profesional` int(7) NOT NULL auto_increment PRIMARY KEY,
`profesional` varchar(200) NOT NULL default '',
`email` varchar(200) NOT NULL default '',
`telefono` int(20) NOT NULL default '0',
);

-- -----------------------------------------------------
-- Table `Warrior`.`cuotas`
-- -----------------------------------------------------
CREATE TABLE `Warrior`.`cuotas` (
`id_cuotas` int(7) NOT NULL auto_increment PRIMARY KEY,
`imagen` BLOB NOT NULL,
);
